version: "3.4"
services:
  api:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      - SPARK_DRIVER_MEMORY=8G
      - SPARK_EXECUTOR_MEMORY=8G
      - SPARK_SQL_SHUFFLE_PARTITIONS=200
      - SPARK_DEFAULT_PARALLELISM=200
      
      
      
      
